Add I test without F/G mode
leon123858/PSY_questionary pull request #96
Opened 2021-05-16 13:37 UTC by linooohon

## Types of Changes

### Add I Test

## Description
1. Add I Test but without F/G mode
- javascripts/CQ_I.js

2. Add images for I Test
- image/I/xx.jpg

3. Add stylesheet for I Test
- stylesheets/style_CQ_ABIHG/style_CQ_I.css

2021-05-17 10:00 UTC, leon123858 requested changes

2021-05-17 10:00 UTC, leon123858 commented on PQ_main/PQ_main/public/javascripts/CQ_I.js
> +}
```
//draw 8
const eight = (speed, isEight) => {
	//定義畫布
	let cvs = document.getElementById('circle');
	let ctx = cvs.getContext('2d');
	cvs.width = window.innerWidth;
	cvs.height = window.innerHeight;
	cvs.style.border = '1px solid #000000';

	let length = 300;
	let time = 0;
	let interval = 0;
	let timer = new Date().getTime();

	//不斷做圓形又清掉又做圓形
	function draw() {
		//不斷改變繪製物件水平位置
		const x = (length * Math.cos(time)) / (1 + Math.pow(2, Math.sin(time)));
		const y =
			(length * Math.cos(time) * Math.sin(time)) /
			(1 + Math.pow(2, Math.sin(time)));
		ctx.clearRect(0, 0, cvs.width, cvs.height);
		ctx.beginPath();
		ctx.fillStyle = 'green';
		isEight
			? ctx.arc(x + cvs.width / 2, cvs.height / 2 + y, 40, 0, 2 * Math.PI, true)
			: ctx.arc(
					y + cvs.width / 2,
					cvs.height / 2 + x,
					40,
					0,
					2 * Math.PI,
					true
			  );

		ctx.closePath();
		ctx.stroke();
		ctx.fill();
		time += 0.01 * speed;
		console.log({ time: time, x: x, y: y });
		if (timer + 30000 < new Date().getTime()) {
			clearInterval(interval);
		}
	}
	interval = setInterval(draw, 30);
};

```

2021-05-17 10:00 UTC, leon123858 commented on PQ_main/PQ_main/public/javascripts/CQ_I.js
> +}
我簡單寫了一測試會動的版本
https://en.wikipedia.org/wiki/Lemniscate_of_Bernoulli
剩下就交給你完善吧
畢竟你也快完成了
我在google查詢的關鍵字 "make objects around figure eight JS CSS"

2021-05-17 10:00 UTC, leon123858 commented on PQ_main/PQ_main/public/javascripts/CQ_I.js
> +}
setInterval 盡量不要以1ms 為間隔, 因為會大於螢幕刷新速率, 所以等於沒有意義
此外也會快於CPU處理速度, 導致 線程(thread)壅塞, 結果就是每個thread的處理速度忽快忽慢, 你若是不理解這段話, 可以問我, 我再口頭跟你解釋

2021-05-20 08:35 UTC, linooohon commented on PQ_main/PQ_main/public/javascripts/CQ_I.js
> +}
剛有推一版修改過後的 I Test
[4ca6abc](https://github.com/leon123858/PSY_questionary/pull/96/commits/4ca6abc86e861f57b2920ed93eebef7643844982)

2021-05-24 04:00 UTC, merged